export type ValidSkills =
  | "Agile Development"
  | "Airflow"
  | "Algorithm Optimization"
  | "Anaconda"
  | "Analytical Skills"
  | "Android Studio"
  | "Angular"
  | "API Integration (Twitter API)"
  | "Application Programming Interfaces (API)"
  | "Appointment Scheduling System Development"
  | "Artificial Intelligence (AI)"
  | "ASP.NET"
  | "AWS"
  | "Azure"
  | "Back-End Web Development"
  | "Backend Development"
  | "Bash/Shell Scripting"
  | "BERT"
  | "Bias Score Metrics"
  | "Billing System Implementation"
  | "Bootstrap"
  | "C"
  | "C#"
  | "C++"
  | "CatBoost"
  | "ChromaDB"
  | "CI/CD"
  | "CML"
  | "Communication"
  | "Computer Vision"
  | "Convolutional Neural Networks (CNN)"
  | "Cross-Device Accessibility"
  | "CSS"
  | "Cypress"
  | "CUDA"
  | "Dart"
  | "Data Analysis"
  | "Data Structures"
  | "Data Visualization"
  | "Databricks"
  | "Deep Learning"
  | "Depth Mapping"
  | "Django"
  | "Docker"
  | "DVC"
  | "Dynamic Programming"
  | "Express.js"
  | "FairSeq"
  | "FastAPI"
  | "Figma"
  | "Firebase"
  | "Flask"
  | "Flutter"
  | "Framer Motion"
  | "Front-End Development"
  | "Frontend Development"
  | "Full-Stack Development"
  | "Game Testing"
  | "GANs" // Added
  | "Generative Adversarial Networks (GANs)"
  | "Git"
  | "Git BASH"
  | "GitHub"
  | "GitHub Actions"
  | "Go"
  | "Google Auth"
  | "Google Charts"
  | "Google Cloud"
  | "Google Colab"
  | "GPT"
  | "Graph Databases"
  | "GraphQL"
  | "HTML5"
  | "Heuristics" // Added
  | "IBM AI Fairness 360"
  | "IoT" // Added
  | "Java"
  | "JavaScript"
  | "Jenkins"
  | "Jest"
  | "JIRA"
  | "jQuery"
  | "Jupyter Notebook"
  | "Keras"
  | "Kubernetes"
  | "LangChain"
  | "Large Language Models (LLM)"
  | "Laravel"
  | "LightGBM"
  | "Linux"
  | "LLaMA"
  | "LLaMA-3.1-8B"
  | "LoRA"
  | "Machine Learning"
  | "Material UI"
  | "MATLAB"
  | "Memory-Augmented Networks"
  | "MLflow"
  | "Model Deployment"
  | "Model Optimization (Pruning, Quantization)"
  | "MongoDB"
  | "Multimodal Data Processing"
  | "MySQL"
  | "Nest.js"
  | "Netlify"
  | "Neural Network Design"
  | "Neural Networks"
  | "Neural Rendering Techniques"
  | "Next.js"
  | "NLP" // Added
  | "Node.js"
  | "NoSQL"
  | "NVIDIA GPU acceleration"
  | "OpenAI API Integration"
  | "OpenCV"
  | "PEFT"
  | "PHP"
  | "PostgreSQL"
  | "Postman"
  | "Power BI"
  | "Predictive Analytics"
  | "Prisma"
  | "Programming"
  | "Prompt Engineering"
  | "PyCharm"
  | "Python"
  | "PyTorch"
  | "Qiskit"
  | "R"
  | "RAG"
  | "React"
  | "React Native"
  | "Real-Time Assistance with WebSockets"
  | "Real-Time Data Processing"
  | "Redis"
  | "Redux"
  | "Reinforcement Learning"
  | "Responsive Web Design"
  | "RLHF"
  | "Robot Operating System (ROS)"
  | "RStudio"
  | "Ruby"
  | "Sass"
  | "Scikit-learn"
  | "scss"
  | "Search Engine Optimization (SEO)"
  | "Selenium"
  | "Semantic Segmentation"
  | "Sentiment Analysis"
  | "Sequence Modeling"
  | "SHAP"
  | "Socket.io"
  | "Spark"
  | "Spring Boot"
  | "SQL"
  | "SQL Server"
  | "Storybook"
  | "Streamlit"
  | "Supabase"
  | "Tableau"
  | "TabNet"
  | "Tailwind CSS"
  | "TensorFlow"
  | "Test Automation"
  | "Three.js"
  | "Transformer Models"
  | "Trello"
  | "TypeScript"
  | "UNIX"
  | "Vercel"
  | "VS Code"
  | "Vue.js"
  | "WebGL"
  | "Webpack"
  | "WordPress"
  | "XAMPP"
  | "XGBoost"
  | "3D Image Reconstruction";

export type ValidCategory =
  | "3D Modeling"
  | "Backend"
  | "Computer Vision"
  | "Data Analysis"
  | "Deep Learning"
  | "FinTech"
  | "Frontend"
  | "Full Stack"
  | "IoT"
  | "ML/AI"
  | "Mobile Dev"
  | "NLP"
  | "Research"
  | "Robotics"
  | "Systems Programming"
  | "UI/UX"
  | "Web Dev";

export type ValidExpType = "Personal" | "Professional" | "Research";

export type ValidPages =
  | "home"
  | "skills"
  | "projects"
  | "experience"
  | "contact"
  | "contributions"
  | "resume"
  | "publications"
  | "blog"
  | "certifications"
  | "timeline";