// Rohan Patil's Site Configuration
export const siteConfig = {
  name: "Rohan Patil | ML Engineer & Researcher",
  authorName: "Rohan Upendra Patil",
  username: "RohanPatil2",
  description:
    "Rohan Patil's portfolio - MS Computer Science student at SUNY Binghamton specializing in Machine Learning, Deep Learning, and MLOps. Research focus on Reinforcement Learning for robotics and bias mitigation in Large Language Models. Published patent holder with expertise in production ML systems.",
  url: "https://rohanpatil.dev", // Update with your actual domain
  links: {
    twitter: "https://twitter.com/rohanpatil", // Update with your handle
    github: "https://github.com/RohanPatil2",
    linkedin: "https://linkedin.com/in/RohanPatil7979",
    email: "rpatil4@binghamton.edu",
  },
  ogImage: "https://rohanpatil.dev/profile-img.jpg", // Update with your domain
  iconIco: "https://rohanpatil.dev/favicon.ico",
  logoIcon: "https://rohanpatil.dev/logo.png",
  keywords: [
    "Rohan Patil",
    "Rohan Upendra Patil",
    "Machine Learning Engineer",
    "Deep Learning",
    "MLOps",
    "Reinforcement Learning",
    "Large Language Models",
    "LLM Fine-tuning",
    "Computer Vision",
    "3D Reconstruction",
    "NeRF",
    "PyTorch",
    "TensorFlow",
    "Python Developer",
    "AI Research",
    "Robotics",
    "AUV Control",
    "Marine Robotics",
    "NLP",
    "RAG",
    "LangChain",
    "Docker",
    "Kubernetes",
    "MLflow",
    "Airflow",
    "AWS",
    "Google Cloud",
    "Azure",
    "Full Stack Developer",
    "SUNY Binghamton",
    "Binghamton University",
    "MS Computer Science",
    "Patent Holder",
    "ML Research",
    "Bias Mitigation",
    "LLaMA",
    "LoRA",
    "Transformer Models",
    "Neural Networks",
    "Data Science",
    "MLOps Pipeline",
    "Model Deployment",
    "FastAPI",
    "React Developer",
    "Next.js Portfolio",
  ],
};
